# Generated by Django 3.1.3 on 2020-11-22 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_auto_20201122_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='following',
            old_name='username',
            new_name='user',
        ),
    ]
