# Generated by Django 3.1.3 on 2020-11-22 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_auto_20201122_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='img',
        ),
    ]
