# Generated by Django 3.1.3 on 2020-11-22 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_remove_image_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
